### PR TITLE
Use event emitters in progress bar to refresh values

### PR DESCRIPTION
**Pull request by joshcosta**
- Refs #16 
- Subscribe to an event emitter in the gradetable component to trigger computational refreshes in the progress bar component
- By using event emitters, we don't need to make sure the computed values are up to date in every getter.

Changes the way information in the progress bar gets updated. This dramatically reduces the number of times Angular thinks it needs to compute values and stops the error linked below from happening.

https://github.com/gradebook/client/issues/16

### CODE REVIEW

**Comment by joshcosta** [comment]
You can see the reduction in computed value updates by console logging something in the updatedComputedValues function in grade-progress-bar

**Comment by vikaspotluri123** [comment]
Does this close #16 or ref it? I'm still seeing issues with when the "what do i need bar" is visible

**Comment by joshcosta** [comment]
Hoping to close it once this PR clears everything up. Can you describe an issue you’re seeing with what do I need?

**Comment by vikaspotluri123** [comment]
New course -> add 3 grades

image

Navigate to a different course

Navigate back to the new course
image

**Pull request merged**
